### ISSUE TITLE
Doesn't work in conda environment

### ISSUE THREAD

**Issue by hovnatan** [hanschen/vim-ipython-cell#1]
I have Anaconda python distribution installed and when I get `ipython-cell requires py >= 2.7 or py3` error on neovim startup with the plugin

**Comment by hanschen** [comment]
What do you get if you run `:python` and `:python3` in neovim?

**Comment by hovnatan** [comment]
`E471: Argument required`

**Comment by hanschen** [comment]
That's weird. I doubt it's related to Anaconda though. What's your neovim version? I found this issue, but it's from a while ago (the `runtime` command isn't required anymore): https://github.com/neovim/neovim/issues/1203

Do other Python plugins work, like YouCompleteMe or UltiSnips?

**Comment by hovnatan** [comment]
I use neovim 0.4. All other plugins work. This plugin works if I'm not in conda environment.

**Comment by hanschen** [comment]
And UltiSnips still works in your conda environment? I ask because it essentially performs the same checks for `has('python')` and `has('python3')`, so I don't understand why UltiSnips would work for you but not this plugin.

Also, have you installed the neovim Python package in your virtual environment?

Finally, you could try to set the path to your Python interpreter:

`let g:python3_host_prog = '/path/to/python3'`

**Comment by hovnatan** [comment]
I made it work with install conda neovim package. Thanks! One more question: is it possible to use `%cpaste` instead of `%paste` in this plugin? I kind of like to see what is being executed.

**Comment by hanschen** [comment]
Good to hear that it's working now. It's currently not possible to use `%cpaste`, but I (or someone else) could quite easily add this feature. Please post a new issue requesting this feature so we can keep track of it.
