### ISSUE TITLE
i Ctrl-C instead of Ctrl-U

### ISSUE THREAD

**Issue by Paul-Aime** [hanschen/vim-ipython-cell#35]
The default behavior is currently to "Send Ctrl-U to clear the line before sending commands to IPython". 
But that fails if the cell has multiple lines.

`Ctrl-C` should be sent instead because it cleans the whole cell.
Actually, `i Ctrl-C` should be sent because the user may use VIM mode for IPython and be in navigation mode

So first send `i` to enter insert mode, then `Ctrl-C` to clear the cell, and finally `%paste -q` to execute the cell.
Right now only `ste -q` is sent (because insert mode is entered only after the `a`)

btw, thanks a lot for the amazing plugin!

**Comment by hanschen** [comment]
Thanks for the suggestion, I'll look into it. I think I considered using `Ctrl-C` in the beginning but don't remember why I decided against it. I think the behavior of `Ctrl-C` has also changed - it used to show the previous input followed by `^C` (actually I prefer this behavior...) rather than clearing everything.

**Comment by hanschen** [comment]
Sorry for the long wait, I've been a bit busy lately.

I've now implemented the feature and made it the default behavior. Please update and see if it works as expected. :)

For people who prefer the old behavior, you can set the following in your `.vimrc` (or equivalent):

``` viml
let g:ipython_cell_send_ctrl_c = 0
let g:ipython_cell_send_ctrl_u = 1
```

**Comment by Paul-Aime** [comment]
After some quick tests, it seems to work like a charm, thanks a lot!
