### ISSUE TITLE
Why use this instead of VSCode's Interactive Python feature?

### ISSUE THREAD

**Issue by ibehnam** [hanschen/vim-ipython-cell#42]
I have installed the Vim extension on VSCode and can create cells via `#%%` and run them in the Interactive environment on the right panel using `SHIFT-ENTER`. I'm curious, what are the advantages of vim-ipython-cell to my current setup?

One killer feature of VSCode is its ability to show images **inside** the same window. With all terminal setups, I've had to one-by-one close the popped-up windows that display graphs in my code. Since vim-ipython-cell's readme talks about its usage in visualizations, I was wondering if it can somehow display images inside the same window, just like VSCode?

**Comment by hanschen** [comment]
The advantage is that you can use Vim/Neovim instead of VSCode + Vim emulation. :)
If VSCode works well for you, then I don't see any reason to switch.

I don't think you can show images inline with IPython's terminal console. You can do it with Qtconsole, but then you need another plugin to connect Vim/Neovim with IPython. See this blog post for more information: https://www.blog.gambitaccepted.com/2020/04/26/neovim-qtconsole-setup/

**Comment by ibehnam** [comment]
I think another reason to stick with VSC is that ipython apparently has a limit on the input string length, so if I want to send vim's long cell code into ipython, it might crash.

**Comment by hanschen** [comment]
I don't think it's an issue with `%paste` (which this plugin uses by default). For `%cpaste`, the plugin sends the code in chunks, so it shouldn't be a problem either. But if you're running a lot of code, you might want to run the whole script anyway (which uses `%run`), so that shouldn't be an issue either.

In the end it really just comes down to which editor you prefer.
