### ISSUE TITLE
Error executing cell on MacOS.

### ISSUE THREAD

**Issue by lkhphuc** [hanschen/vim-ipython-cell#5]
Hi, I'm getting this error when trying to execute cell:
```
Error detected while processing function IPythonCellExecuteCell:
line    1:
Could not find xclip or xsel executable
```

In my IPython console, I see the content of my system clipboard pasted instead of the code cell.
However I'm using the Vim-Slime alone just fine, code can be selected and send to IPython terminal using barebone Slime no problem.

Do you know why it's complaining about xclip or xsel, shouldn't everything just communicate through Slime?

Thanks a lot.

**Comment by hanschen** [comment]
The `IPythonCellExecuteCell` command requires xclip or xsel to copy the cell to the system clipboard, which is then executed by IPython using `%paste -q`.

It's also possible to send the code in the cell to IPython using Slime and `%cpaste`, but then you would see the whole code snippet each time instead of just `%paste -q`, which I personally find a bit distracting. With that said, I've thought about adding support for this "verbose" cell execution for people without xclip or xsel. Feel free to create an Issue for this feature to keep track of it.

For now you could try to install e.g. xclip using Homebrew: https://formulae.brew.sh/formula/xclip

**Comment by lkhphuc** [comment]
Thank a lot.
